# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0849814706ae6f926f16754ec9559269b5cae926cc805cbc643dcdfa050c6e83801efe4a7b3d4c702c88f7e0d0f463fbf43084bfa09487523ced32e8de71155

test:
  secret_key_base: 6e7bc74a32208e22ab17be5ef99f5f52930181b20d7231fe847ce2eea63df42b1bc9257a81c2762acf065b9868206fe2ef02830e6f676e9410b5109b75bc5aeb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
